# aergo TOML Configration File (https://github.com/toml-lang/toml)
# base configurations
datadir = "_data_"
enableprofile = true
profileport = 10102
#loglevel = "info"
#loglevel = "debug,CHAINSVC=debug,MEMPOOLSVC=error"
enablerest = true
[rest]
restport = 10202


[rpc]
netserviceaddr = "0.0.0.0"
netserviceport = 10002
nstls = false
nscert = ""
nskey = ""
nsallowcors = false

[p2p]
netprotocoladdr = "127.0.0.1"
netprotocolport = 11002
nptls = false
npcert = ""
npkey = "11002.key"
npaddpeers = [
"/ip4/127.0.0.1/tcp/11001/p2p/16Uiu2HAkvaAMCHkd9hZ6hQkdDLKoXP4eLJSqkMF1YqkSNy5v9SVn","/ip4/127.0.0.1/tcp/11003/p2p/16Uiu2HAmA2ysmFxoQ37sk1Zk2sMrPysqTmwYAFrACyf3LtP3gxpJ","/ip4/127.0.0.1/tcp/11004/p2p/16Uiu2HAmQti7HLHC9rXqkeABtauv2YsCPG3Uo1WLqbXmbuxpbjmF","/ip4/127.0.0.1/tcp/11005/p2p/16Uiu2HAmRm9iKQdfLpeTZUW1YA2TDWabLskzNpizSiFd9nLo6mPy"
]

[blockchain]
# blockchain configurations
blockchainplaceholder = false
maxblocksize = 1000000
usefastsyncer= true
[mempool]
showmetrics = true
[consensus]
enablebp = true
#blockinterval = 1

[consensus.raft]
newcluster=true
blockintervalms = 1000
name="aergo2"
listenurl="http://0.0.0.0:13002"
snapfrequency=10
#
